mysite/groups/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'events', views.EventViewSet, basename='event')

app_name = 'groups'
urlpatterns = [
    path('groups/', views.GroupListView.as_view(), name='group-list'),
    path('group/<int:pk>/', views.GroupDetailView.as_view(), name='group-detail'),
    path('group/new/', views.GroupCreateView.as_view(), name='group-create'),
    path('group/<int:pk>/update/',
         views.GroupUpdateView.as_view(), name='group-update'),
    path('group/<int:pk>/delete/',
         views.GroupDeleteView.as_view(), name='group-delete'),
    path('group/<int:pk>/leave/', views.group_leave, name='group-leave'),
    path('group/<int:pk>/join/', views.group_join, name='group-join'),
    path('api/', include(router.urls)),
]

mysite/main/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', TemplateView.as_view(template_name='main/faq.html'), name='faq'),
    path('about', TemplateView.as_view(template_name='main/about.html'), name='about'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/user/<str:username>',
         views.UserPostListView.as_view(), name='user-post-list'),
    path('posts/topic/<str:topic>',
         views.TopicPostListView.as_view(), name='topic-post-list'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/', views.comment, name='post-comment'),
    path('comment/<int:pk>/update/',
         views.CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/',
         views.CommentDeleteView.as_view(), name='comment-delete'),
    path('videochat/', views.videochat, name='videochat'),
    path('jitsi/<str:room>', views.jitsi, name='jitsi'),
    path('privacy/', TemplateView.as_view(template_name='main/privacy.html'), name='privacy'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('', include('groups.urls')),
    path('favicon.ico', RedirectView.as_view(
        url=staticfiles_storage.url('favicon.ico'))),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/main/models.py
from random import choice

from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


class Topic(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(
        User, verbose_name='Szerző', on_delete=models.CASCADE)
    title = models.CharField('Cím', max_length=300)
    topic = models.ForeignKey(
        Topic, verbose_name='Téma', on_delete=models.SET_NULL, null=True, blank=True)
    body = models.TextField('Tartalom')
    pub_date = models.DateTimeField('Közzétételi dátum', default=timezone.now)

    class Meta:
        ordering = ['-pub_date', 'author']

    def __str__(self):
        return self.title + ' - #' + str(self.id)

    def get_absolute_url(self):
        return reverse('main:post-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    author = models.ForeignKey(
        User, verbose_name='Szerző', on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey(
        Post, verbose_name='Poszt', on_delete=models.CASCADE, related_name='comments')
    text = models.TextField('Tartalom')
    pub_date = models.DateTimeField('Közzétételi dátum', default=timezone.now)

    class Meta:
        ordering = ['-pub_date', 'author']

    def get_absolute_url(self):
        return reverse('main:post-detail', kwargs={'pk': self.post.pk}) + '#comment-' + str(self.pk)


class Tip(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:25]

    @staticmethod
    def get_a_tip():
        DEFAULT_TIPS = ['Legyen mindig nyitott, akárcsak a forráskódja!',
                        'Szabad ország, szabad szoftver!', 'Az élet szép.']
        tip = Tip.objects.order_by('?').first()
        if tip:
            tip = tip.text
        else:
            tip = choice(DEFAULT_TIPS)
        return tip

mysite/main/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class VideochatCodeForm(forms.Form):
    code = forms.CharField(max_length=50, label='Megbeszéléskód')

mysite/main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import CommentForm, VideochatCodeForm
from .models import Comment, Post, Tip, Topic


def home(request):
    tip = Tip.get_a_tip()
    return render(request, 'main/home.html', context={'tip': tip})


class PostListView(ListView):
    model = Post
    ordering = ['-pub_date']
    paginate_by = 3


class UserPostListView(ListView):
    model = Post
    template_name = 'main/user_post_list.html'
    ordering = ['-pub_date']
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.kwargs.get('username')
        return context


class TopicPostListView(ListView):
    model = Post
    template_name = 'main/topic_post_list.html'
    ordering = ['-pub_date']
    paginate_by = 3

    def get_queryset(self):
        topic = get_object_or_404(Topic, name=self.kwargs.get('topic'))
        return Post.objects.filter(topic=topic)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topic'] = self.kwargs.get('topic')
        return context


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm()
    return render(request, 'main/post_detail.html', context={'object': post, 'form': form})


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'topic', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'topic', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author or self.request.user.is_staff and not post.author.is_superuser


@login_required
def comment(request, pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.instance.post = post
            form.save()
            messages.success(request, 'Komment létrehozva.')
    return redirect('main:post-detail', pk=pk)


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['text']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        return reverse('main:post-detail', kwargs={'pk': self.object.post.pk})

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author or self.request.user.is_staff and not (comment.author and comment.author.is_superuser)


def videochat(request):
    if request.method == 'POST':
        form = VideochatCodeForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            return redirect('main:jitsi', code)
    else:
        form = VideochatCodeForm()
    return render(request, 'main/videochat.html', context={'form': form})


def jitsi(request, room):
    return render(request, 'main/jitsi.html', context={'room': room, 'email': request.user.email, 'username': request.user.username})

mysite/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    {% block css %}{% endblock %}
    {% block title %}<title>Helló, Világ!</title>{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a href="{% url 'main:home' %}" class="navbar-brand mr-4">NISZ</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="navbar-nav mr-auto">
                    <a href="{% url 'main:home' %}" class="nav-item nav-link">Kezdőlap</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Közösség
                        </a>
                        <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
                            <a href="{% url 'main:post-list' %}" class="dropdown-item">Posztok</a>
                            <a href="{% url 'groups:group-list' %}" class="dropdown-item">Csoportok</a>
                            <a href="{% url 'main:faq' %}" class="dropdown-item">GY.I.K.</a>
                            {% if user.is_authenticated %}
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'main:videochat' %}" class="dropdown-item">Videóhívás</a>
                            {% endif %}
                        </div>
                    </li>
                    <a href="{% url 'main:about' %}" class="nav-item nav-link">Rólunk</a>
                </ul>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                            <a href="{% url 'admin:index' %}" class="nav-item nav-link">Admin</a>
                        {% endif %}
                        <a href="{% url 'profile' user.id %}" class="nav-item nav-link">Profil</a>
                        <a href="{% url 'logout' %}" class="nav-item nav-link">Kijelentkezés</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="nav-item nav-link">Bejelentkezés</a>
                        <a href="{% url 'register' %}" class="nav-item nav-link">Regisztráció</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <!--<div class="text-center">
                    <iframe src="https://free.timeanddate.com/countdown/i7r9j7cb/n50/cf12/cm0/cu4/ct0/cs1/ca0/cr0/ss0/cac000/cpc000/pcfff/tcfff/fs200/szw576/szh243/tac000/tpc000/mac000/mpc000/iso2021-04-11T10:00:00" allowtransparency="true" frameborder="0" width="394" height="173"></iframe>
                </div>-->
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js" integrity="sha512-XKa9Hemdy1Ui3KSGgJdgMyYlUg1gM+QhL6cnlyTe2qzMCYm4nAZ1PsVerQzTTXzonUR+dmswHqgJPuwCq1MaAg==" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
</body>

</html>

mysite/main/templates/main/comment_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <h2 class="text-center">Csoportok</h2>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <h3>Biztosan törölni szeretné a {% if object.author and object.author != user %} "{{ object.author }}" felhasználóhoz tartozó {% endif %} kommentet?</h3>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-danger">Igen</button>
            <a href="{% url 'main:post-detail' object.id %}" class="btn btn-outline-secondary">Mégsem</a>
        </div>
    </form>
{% endblock %}

mysite/main/templates/main/post_detail.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="border-bottom mb-4">
        <h2 class="mb-1">{{ object.title }}</h2>
        <p class="text-muted mb-1">Szerző: <a href="{% url 'main:user-post-list' object.author.username %}" class="text-primary">{{ object.author.username }}</a></p>
        <p class="text-muted mb-1">Létrehozva: {{ object.pub_date|date:"Y. m. d." }}</a></p>
        {% if object.topic %}
            <a href="{% url 'main:topic-post-list' object.topic.name %}"><div class="badge badge-pill badge-warning">{{ object.topic.name }}</div></a>
        {% endif %}
    </div>
    <p class="p-1 rounded bg-light">{{ object.body|linebreaksbr }}</p>
    {% if object.author == user %}
        <a href="{% url 'main:post-update' object.id %}" class="btn btn-secondary btn-sm mt-1 mb-1"><i class="far fa-edit"></i> Módosítás</a>
        <a href="{% url 'main:post-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1"><i class="far fa-trash-alt"></i> Törlés</a>
    {% elif user.is_staff and not object.author.is_superuser %}
        <a href="{% url 'main:post-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1"><i class="far fa-trash-alt"></i> Törlés</a>
    {% endif %}

    <div class="border-bottom mb-4">
        <h3 class="mb-1">Hozzászólások</h3>
    </div>
    <div class="my-4 py-3 px-3 jumbotron">
        {% if user.is_authenticated %}
            <form action="{% url 'main:post-comment' object.id %}" method="POST">
                {% csrf_token %}

                {{ form|crispy }}

                <button type="submit" class="btn btn-block btn-success">Hozzászólás</button>
            </form>
        {% else %}
            A kommenteléshez <a href="{% url 'login' %}?next={{ request.path }}">jelentkezzen be</a> vagy <a href="{% url 'register' %}">regisztráljon</a>!
        {% endif %}
    </div>
    {% for comment in object.comments.all %}
        <div id="comment-{{ comment.id }}" class="border border-secondary rounded px-4 py-1 my-2">
            <h4 class="mb-1">
                {% if comment.author %}
                    <a href="{% url 'main:user-post-list' comment.author.username %}" class="text-dark">{{ comment.author.username }}</a>
                    {% if comment.author == object.author %}
                        <small class="fas fa-check-square text-primary" title="Szerző"></small>
                    {% endif %}
                {% else %}
                    <span class="text-muted">Törölt felhasználó <small class="far fa-times-circle" title="Törölt felhasználó"></small></span>
                {% endif %}
            </h4>
            <p class="p-1 rounded bg-light">{{ comment.text|linebreaksbr }}</p>
            {% if comment.author == user %}
                <a href="{% url 'main:comment-update' comment.id %}" class="text-secondary">
                    <i class="far fa-edit"></i> Módosítás
                </a>
                <a href="{% url 'main:comment-delete' comment.id %}" class="text-danger">
                    <i class="far fa-trash-alt"></i> Törlés
                </a>
            {% elif user.is_staff and not comment.author.is_superuser %}
                <a href="{% url 'main:comment-delete' comment.id %}" class="text-danger">
                    <i class="far fa-trash-alt"></i> Törlés
                </a>
            {% endif %}
            <p class="text-muted float-right">{{ comment.pub_date }}</p>
            <br>
        </div>
    {% empty %}
        <i class="text-muted">Még senki nem szólt hozzá.</i>
    {% endfor %}
{% endblock %}

mysite/main/templates/main/post_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center">Poszt létrehozása</h2>
    <hr>
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-block btn-outline-info">
            <i class="fas fa-plus-circle"></i> Létrehozás
        </button>
    </form>
{% endblock %}

mysite/main/templates/main/post_list.html
{% extends 'main/base.html' %}

{% block content %}
    <h2 class="text-center">Posztok</h2>
    <hr>

    {% for post in object_list %}
        <article class="my-2">
            <div class="card">
                <div class="card-header p-2">
                    <a href="{% url 'main:user-post-list' post.author.username %}" class="text-secondary"><img src="{{ post.author.profile.image.url }}" alt="" class="img-thumbnai rounded-circle" style="max-width: 32px;"></a>
                    <a class="ml-1" href="{% url 'main:user-post-list' post.author.username %}"><strong class="text-primary">{{ post.author }}</strong></a>
                </div>
                <div class="card-body p-2">
                    <a href="{% url 'main:post-detail' post.id %}" class="text-dark"><h5 class="card-title">{{ post.title }}</h5></a>
                    <p class="card-text">{{ post.body|slice:":170" }}{% if post.body|length > 170 %}...{% endif %}</p>
                </div>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        <nav class="bg-light mt-3" aria-label="További oldalak">
            <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Előző">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Előző</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Előző">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Előző</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Következő">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Következő</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Következő">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Következő</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'main:post-create' %}" class="btn btn-block btn-primary mt-3 mb-4">Új poszt létrehozása</a>
    {% endif %}
{% endblock %}

mysite/main/templates/main/topic_post_list.html
{% extends 'main/base.html' %}

{% block content %}
    <h2 class="text-center">{{ topic }} posztok</h2>
    <hr>

    {% for post in object_list %}
        <article class="my-2">
            <div class="card">
                <div class="card-header p-2">
                    <a href="{% url 'main:user-post-list' post.author.username %}" class="text-secondary"><img src="{{ post.author.profile.image.url }}" alt="" class="img-thumbnai rounded-circle" style="max-width: 32px;"></a>
                    <a class="ml-1" href="{% url 'main:user-post-list' post.author.username %}"><strong class="text-primary">{{ post.author }}</strong></a>
                </div>
                <div class="card-body p-2">
                    <a href="{% url 'main:post-detail' post.id %}" class="text-dark"><h5 class="card-title">{{ post.title }}</h5></a>
                    <p class="card-text">{{ post.body|slice:":170" }}{% if post.body|length > 170 %}...{% endif %}</p>
                </div>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        <nav class="bg-light mt-3" aria-label="További oldalak">
            <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

mysite/main/templates/main/user_post_list.html
{% extends 'main/base.html' %}

{% block content %}
    <h2 class="text-center">{{ username }} posztjai</h2>
    <hr>

    {% for post in object_list %}
        <article class="my-2">
            <div class="card">
                <div class="card-header p-2">
                    <a href="{% url 'main:user-post-list' post.author.username %}" class="text-secondary"><img src="{{ post.author.profile.image.url }}" alt="" class="img-thumbnai rounded-circle" style="max-width: 32px;"></a>
                    <a class="ml-1" href="{% url 'main:user-post-list' post.author.username %}"><strong class="text-primary">{{ post.author }}</strong></a>
                </div>
                <div class="card-body p-2">
                    <a href="{% url 'main:post-detail' post.id %}" class="text-dark"><h5 class="card-title">{{ post.title }}</h5></a>
                    <p class="card-text">{{ post.body|slice:":170" }}{% if post.body|length > 170 %}...{% endif %}</p>
                </div>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        <nav class="bg-light mt-3" aria-label="További oldalak">
            <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}