mysite/groups/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'events', views.EventViewSet, basename='event')

app_name = 'groups'
urlpatterns = [
    path('groups/', views.GroupListView.as_view(), name='group-list'),
    path('group/<int:pk>/', views.GroupDetailView.as_view(), name='group-detail'),
    path('group/new/', views.GroupCreateView.as_view(), name='group-create'),
    path('group/<int:pk>/update/',
         views.GroupUpdateView.as_view(), name='group-update'),
    path('group/<int:pk>/delete/',
         views.GroupDeleteView.as_view(), name='group-delete'),
    path('group/<int:pk>/leave/', views.group_leave, name='group-leave'),
    path('group/<int:pk>/join/', views.group_join, name='group-join'),
    path('api/', include(router.urls)),
]

mysite/main/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', TemplateView.as_view(template_name='main/faq.html'), name='faq'),
    path('about', TemplateView.as_view(template_name='main/about.html'), name='about'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/user/<str:username>',
         views.UserPostListView.as_view(), name='user-post-list'),
    path('posts/topic/<str:topic>',
         views.TopicPostListView.as_view(), name='topic-post-list'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/', views.comment, name='post-comment'),
    path('comment/<int:pk>/update/',
         views.CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/',
         views.CommentDeleteView.as_view(), name='comment-delete'),
    path('videochat/', views.videochat, name='videochat'),
    path('jitsi/<str:room>', views.jitsi, name='jitsi'),
    path('privacy/', TemplateView.as_view(template_name='main/privacy.html'), name='privacy'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('', include('groups.urls')),
    path('favicon.ico', RedirectView.as_view(
        url=staticfiles_storage.url('favicon.ico'))),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/groups/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


class Group(models.Model):
    name = models.CharField('Név', max_length=50, unique=True)
    description = models.TextField('Leírás', max_length=500, blank=True)
    owner = models.ForeignKey(
        User, verbose_name='Tulajdonos', on_delete=models.CASCADE, related_name='owned_groups')
    users = models.ManyToManyField(
        User, verbose_name='Tagok', through='UserGroup')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('groups:group-detail', kwargs={'pk': self.pk})

    def get_member(self, user):
        return UserGroup.objects.filter(user=user, group=self).first()

    def user_is_member(self, user):
        return self.get_member(user)


class UserGroup(models.Model):
    user = models.ForeignKey(
        User, verbose_name='Felhasználó', on_delete=models.CASCADE, related_name='usergroups')
    group = models.ForeignKey(
        Group, verbose_name='Csoport', on_delete=models.CASCADE)
    join_date = models.DateField(default=timezone.now)

    def __str__(self):
        return '%s - %s' % (self.user.username, self.group.name)


class Event(models.Model):
    title = models.CharField('Cím', max_length=100)
    owner = models.ForeignKey(
        User, verbose_name='Létrehozó', on_delete=models.CASCADE, related_name='events')
    group = models.ForeignKey(
        Group, verbose_name='Csoport', on_delete=models.CASCADE, related_name='events')
    start = models.DateTimeField('Kezdeti dátum')
    end = models.DateTimeField('Végső dátum')

    class Meta:
        ordering = ['end']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.start > self.end:
            raise ValidationError(
                'Nem kezdődhet később, mint a befejezés időpontja.')
        super(Event, self).save(*args, **kwargs)

mysite/groups/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from rest_framework import serializers, viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from .models import Event, Group, UserGroup
from .permissions import IsOwnerOrReadOnly


class GroupListView(ListView):
    model = Group
    ordering = ['name']
    paginate_by = 8

    def get_queryset(self):
        queryset = Group.objects.all()
        q = self.request.GET.get('q')
        if q:
            queryset = queryset.filter(
                Q(name__icontains=q) | Q(description__icontains=q))
        return queryset


class GroupDetailView(DetailView):
    model = Group

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_member'] = self.request.user.is_authenticated and self.object.user_is_member(
            self.request.user)
        return context


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class GroupUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Group
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        group = self.get_object()
        return self.request.user == group.owner


class GroupDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Group

    def get_success_url(self):
        return reverse('groups:group-list')

    def test_func(self):
        group = self.get_object()
        return self.request.user == group.owner or self.request.user.is_staff and not group.author.is_superuser


@login_required
def group_leave(request, pk):
    group = get_object_or_404(Group, pk=pk)
    if request.user != group.owner:
        conn = group.get_member(request.user)
        if conn:
            conn.delete()
            messages.success(request, 'Sikeresen elhagyta a csoportot.')
    return redirect('groups:group-list')


@login_required
def group_join(request, pk):
    group = get_object_or_404(Group, pk=pk)
    if request.user != group.owner:
        conn = group.get_member(request.user)
        if not conn:
            conn = UserGroup(user=request.user, group=group)
            conn.save()
            messages.success(request, 'Sikeresen csatlakozott a csoporthoz.')
    return redirect('groups:group-detail', pk=group.id)


class EventViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

    def get_queryset(self):
        queryset = Event.objects.all()
        if self.action == 'list':
            group = self.request.query_params.get('group')
            if group:
                queryset = queryset.filter(group__id=group)
            start = self.request.query_params.get('start')
            if start:
                queryset = queryset.filter(end__gte=
                    datetime.utcfromtimestamp(int(start) // 1e3))
            end = self.request.query_params.get('end')
            if end:
                queryset = queryset.filter(start__lte=
                    datetime.utcfromtimestamp(int(end) // 1e3))
        return queryset

    def get_serializer_class(self):
        group_choices = [x.group for x in self.request.user.usergroups.all(
        )] if self.request.user.is_authenticated else []

        class EventSerializer(serializers.ModelSerializer):
            group = serializers.ChoiceField(group_choices, write_only=True)
            owner_name = serializers.ReadOnlyField(
                source='owner.username')

            class Meta:
                model = Event
                fields = ['id', 'title', 'group',
                          'owner_name', 'start', 'end']

        return EventSerializer

mysite/groups/templates/groups/group_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <h2 class="text-center">Csoport törlése</h2>
    <hr>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <h3>Biztosan törölni szeretné a {% if object.owner != user %} "{{ object.owner }}" felhasználóhoz tartozó {% endif %} "{{ object.name }}" csoportot?</h3>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-danger">Igen</button>
                <a href="{% url 'groups:group-detail' object.id %}" class="btn btn-outline-secondary">Mégsem</a>
            </div>
        </form>
    </div>
{% endblock %}

mysite/groups/templates/groups/group_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center">Csoport létrehozása</h2>
    <hr>
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-block btn-outline-info">
            <i class="fas fa-plus-circle"></i> Létrehozás
        </button>
    </form>
{% endblock %}

mysite/groups/templates/groups/group_list.html
{% extends 'main/base.html' %}

{% block content %}
    <h2 class="text-center">Csoportok</h2>
    <hr>

    <form method="GET" class="mb-3">
        <div class="input-group">
            <input type="search" class="form-control" name="q" placeholder="Keresés">
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <div class="row">
        {% for group in object_list %}
            <div class="col-md-3 py-3">
                <div class="card rounded p-1" style="height: 100%;">
                    <div class="card-body">
                        <a href="{% url 'groups:group-detail' group.id %}" class="text-dark"><h5 class="card-title">{{ group.name }}</h5></a>
                        <p class="text-muted">{{ group.owner.username }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if is_paginated %}
        <nav class="bg-light mt-3" aria-label="További oldalak">
            <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Előző">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Előző</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Előző">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Előző</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Következő">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Következő</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Következő">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Következő</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'groups:group-create' %}" class="btn btn-block btn-primary mt-3 mb-4">Új csoport létrehozása</a>
    {% endif %}
{% endblock %}